### PR TITLE
Blindly click through some dialog boxes during donation process, to f…

### PR DESCRIPTION
**Pull request by bdsl**
…ix failing tests

### CODE REVIEW

**Comment by NoelLH** [comment]
Thanks for trying to sort this @bdsl!

Unfortunately this was not an easy one at all because I think there are 2 things going on that have made this broken and/or unstable at various points over the last week:

1. We introduced a wrapper for modal content that means it's now in the shadow DOM. This makes the elements frustratingly hard to target for _certain_ kinds of usage (interact-able for input) without workarounds, but I've tried to address it on https://github.com/thebiggive/regression-tests/pull/70 – I used some local workaround steps to target staging temporarily for certain pieces of the journeys, due to point (2), to try to get step logic that works.
2. It seems like the Regression database instance used by MatchBot and Identity services is misbehaving, and there have been weird but intermittent connection dropped errors some of the time. I've opened an AWS Case to see if their support can shed any light on this.

**Comment by bdsl** [comment]
Thanks @NoelLH . Closing in favour of https://github.com/thebiggive/regression-tests/pull/70

**Comment by bdsl** [comment]
This doesn't seem to be helping - there 4 tests just failed on this PR branch which is the same as we've been getting on main.

**Comment by NoelLH** [comment]
> This doesn't seem to be helping - there 4 tests just failed on this PR branch which is the same as we've been getting on main.

@bdsl  We do already have code to close these dialogs on `main`.

Have you checked CircleCI and TestingBot to see the specific ways the scheduled tests are failing, to try to work out if this part is relevant?

**Comment by bdsl** [comment]
> > This doesn't seem to be helping - there 4 tests just failed on this PR branch which is the same as we've been getting on main.
> 
> @bdsl We do already have code to close these dialogs on `main`.
> 
> Have you checked CircleCI and TestingBot to see the specific ways the scheduled tests are failing, to try to work out if this part is relevant?

Yes I viewed the recordings in testingbot and left some notes in Slack at https://thebiggive.slack.com/archives/C04BETLU4UC/p1669371598913389

**Pull request closed without merging**
