### PR TITLE
REG-23 – add Axe accessibility checks

### PR DESCRIPTION
**Pull request by NoelLH**

### CODE REVIEW

**Review by bdsl — APPROVED** [review]
Looks good as far as it goes - I've been wanting to try axe-core for a few years. Am I right to think this doesn't by itself complete REG-23?

**Comment by NoelLH** [comment]
> Looks good as far as it goes - I've been wanting to try axe-core for a few years. Am I right to think this doesn't by itself complete REG-23?

@bdsl Yeah, please see my comments including a frontend PR and potential strategic blocker on Jira.

**Comment by alihejazi** [comment]
@NoelLH LGTM, but do you only wish to run these checks on the DonateStartPage? What about all the others?

**Comment by NoelLH** [comment]
> @NoelLH LGTM, but do you only wish to run these checks on the DonateStartPage? What about all the others?

@alihejazi The idea was to get something that works out first and then assess other areas where it might be valuable iteratively. It's a bit academic where else we should focus until we have the first place passing these checks.

**Pull request merged**
